import Head from "next/head"
import { Geist, Geist_Mono } from "next/font/google"
import styles from "../styles/Home.module.css"
import { DungeonSelect } from "../components/dungeonSelect/dungeonSelect"
import { useState } from "react"
import { DungeonLengthType, DungeonType } from "../types"
import { CONFIG } from "../config"
import { DungeonLengthSelect } from "../components/dungeonLengthSelect/dungeonLengthSelect"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export default function Home() {
  const [dungeon, setDungeon] = useState<DungeonType>(CONFIG.dungeon.RUINS)
  const [dungeonLength, setDungeonLength] = useState<DungeonLengthType>(
    CONFIG.dungeonLength.SHORT
  )

  const provisions = CONFIG.dungeonProvisions.find((p) => p.dungeon === dungeon && p.dungeonLength === dungeonLength)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <DungeonSelect dungeon={dungeon} setDungeon={setDungeon} />
          <DungeonLengthSelect
            dungeonLength={dungeonLength}
            setDungeonLength={setDungeonLength}
          />

          {provisions && (
            <div>
              <h2>
                {dungeon} - {dungeonLength}
              </h2>
              <ul>
                {provisions.provisions.map((p) => (
                  <li key={p.provision.name}>
                    <h3>{p.provision.name}</h3>
                    <p>
                      {p.min} - {p.max}
                    </p>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </main>
      </div>
    </>
  )
}
